### ISSUE TITLE
Drop Google Analytics

### ISSUE THREAD

**Issue by irydacea** [wesnoth/wesmere#18]
To my knowledge, nobody has had access to GA or used the info therein in over a decade, not to mention that script and ad blockers are likely to make it mildly inaccurate. As it is, right now it just contributes to page load times and adds unnecessary 3rd party tracking.

(This change would impact the front page, the Wesmere MW template, and the Wesmere extension at <https://github.com/shikadiqueen/weldyn2-extensions>.)

**Comment by cooljeanius** [comment]
If it's desired to still use some sort of analytics that's not Google Analytics, IIRC the FSF recommends the use of Piwik Analytics instead: https://www.fsf.org/blogs/licensing/interview-with-matthieu-aubry-of-piwik
(or I guess it's called "Matomo" now)

**Comment by Pentarctagon** [comment]
No objections here.  I know I at least have had this blocked via noscript since always.
