### ISSUE TITLE
Hitting Tab at Login Screen

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesmere#8]
Hello,
This may be minor, but hitting the tab key after entering one's account name should probably go to the password field, but instead that moves to the search button (the magnifying glass, not even the search field).  At least it does for me (SuSE/Firefox 52.3...  not sure what other info you would need.)

**Comment by irydacea** [comment]
Wiki or forums?

**Comment by doofus-01** [comment]
Both, it seems.

**Comment by irydacea** [comment]
This is fixed in production now.
