### ISSUE TITLE
Increase visibilty of "Contributions"

### ISSUE THREAD

**Issue by doofus-01** [wesnoth/wesmere#9]
This is a suggestion for content, not site functionality, I apologize if this isn't the right venue.

If Wesnoth needs contributors as much as customers/players (and I think it still does) shouldn't a link be up near the "Download Now!" button?  All the relevant info and links are included at the bottom of the page, but it would help to have one of the wiki/forum links advertised on almost-equal footing as the download button.

**Comment by irydacea** [comment]
I feel like this is better suited for a forum thread and handled by @Vultraz since he's the Community Manager.

**Comment by doofus-01** [comment]
Vultraz doesn't seem to think contributions need to be promoted, so that's that.  I think that's wrong (obviously), but who am I to blow against the wind?  I'd close this, but maybe it's better left open in case there are different people involved in the future.  If you want to close it though, @shikadilord , I won't be insulted.

**Comment by irydacea** [comment]
You might want to tone down on that passive-aggressiveness every time an issue or PR of yours gets turned down.

**Comment by doofus-01** [comment]
What?
